hooks:
  ApplicationStop:
    - location: scripts/purge_venv.sh
      timeout: 30
      runas: ec2-user
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ec2-user

